# fly.toml app configuration file generated for train-simulator on 2024-06-11T18:13:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'train-simulator'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 5000

  [[services.ports]]
    port = 5000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
