= Train Simulator
:toc:

== CI/CD Status

image::https://github.com/jurisk/train-simulator/actions/workflows/rust.yml/badge.svg[Rust,link=https://github.com/jurisk/train-simulator/actions/workflows/rust.yml]

https://jurisk.github.io/train-simulator-pages/[Online version]

== Useful commands

=== Housekeeping

Rare:

[source,bash]
----
rustup update
cargo update
cargo udeps --all-targets
cargo audit
cargo tree --duplicates
----

Frequent:

[source,bash]
----
cargo +nightly fmt
cargo clippy -- -W clippy::pedantic -W clippy::style -W clippy::unwrap_used -W clippy::expect_used
----

=== Running

[NOTE]
====
Do not forget to use `--features bevy/dynamic_linking` when running from the IDE.
====

[source,bash]
----
cargo run --features bevy/dynamic_linking --package networking-server --bin server_console
cargo run --features bevy/dynamic_linking --package networking-client --bin client_graphical
cargo run --features bevy/dynamic_linking --package client-single-player --bin client_single_player
----

=== Install Prerequisites

On macOS:

[source,bash]
----
brew install llvm
----

From https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional[Enable Fast Compiles]:

[source,bash]
----
cargo install -f cargo-binutils
rustup component add llvm-tools-preview
----

From https://github.com/bevyengine/bevy/tree/main/examples#wasm[WASM examples]:

[source,bash]
----
rustup target add wasm32-unknown-unknown
cargo install wasm-bindgen-cli
----

=== WASM build

Later: Consider using `wasm-pack` and `wasm-opt` as described in https://github.com/UkoeHB/enfync?tab=readme-ov-file#recommended-wasm-build[`enfync` docs]:

[source,bash]
----
cargo build --profile wasm-release --target wasm32-unknown-unknown --package client-single-player --package networking-client --bin client_single_player --bin client_graphical
wasm-bindgen --out-name client_single_player --out-dir static/wasm-build --target web target/wasm32-unknown-unknown/wasm-release/client_single_player.wasm
wasm-bindgen --out-name client_graphical --out-dir static/wasm-build --target web target/wasm32-unknown-unknown/wasm-release/client_graphical.wasm
----

=== Dependency tree

Not sure why, but the resulting `.dot` files would open in the JetBrains IDE plug-in, but not with the `dot` command-line tool.

[source,bash]
----
cargo install cargo-depgraph
cargo depgraph --all-deps
cargo depgraph --all-deps --dedup-transitive-deps
cargo depgraph --workspace-only
dot -Tsvg input.dot -o output.svg
----

Later: Could add a CI action to check that the `--workspace-only` graph hasn't changed and isn't circular.

=== Visualise structure

Example, for the `game-logic` package:

[source,bash]
----
cargo install cargo-modules
cargo modules dependencies --no-externs --no-fns --no-sysroot --no-traits --no-types --no-uses --package game-logic > game-logic-module.dot
----

=== Package and run as Docker

Building and running the Docker image:

[source,bash]
----
docker build --tag train-simulator .
docker image ls train-simulator
docker run --interactive --tty --rm --name train-simulator --publish 8080:8080/tcp train-simulator
docker stop train-simulator
----

Pruning, as Rancher tends to eat up all available space:

[source,bash]
----
docker system prune -f
docker builder prune -f
----

== Deploy to Kubernetes on Google Cloud Platform

=== Overall pre-requisites

Install https://cloud.google.com/sdk/docs/install-sdk[Google Cloud SDK].

[source,bash]
----
gcloud auth login
gcloud config set project train-simulator-gcp
----

=== Helm charts

#TODO: Incomplete section as I figure it out.#

[source,bash]
----
gcloud iam service-accounts create gcr-reader --display-name "GCR Reader"
gcloud projects add-iam-policy-binding train-simulator-gcp --member="serviceAccount:gcr-reader@train-simulator-gcp.iam.gserviceaccount.com" --role="roles/artifactregistry.reader"
gcloud iam service-accounts keys create gcp-reader-key-file.json --iam-account gcr-reader@train-simulator-gcp.iam.gserviceaccount.com
kubectl create secret docker-registry gcr-json-key --docker-server=gcr.io --docker-username=_json_key --docker-password="$(cat gcp-reader-key-file.json)" --docker-email=gcr-reader@train-simulator-gcp.iam.gserviceaccount.com
kubectl get secret gcr-json-key
helm lint ./charts/game-service
helm template game-service ./charts/game-service
helm install game-service ./charts/game-service --set environment=local
helm install game-service ./charts/game-service --set environment=production
helm uninstall game-service
----

=== Build and push Docker image

[source,bash]
----
gcloud services enable artifactregistry.googleapis.com
gcloud auth configure-docker
docker build --tag train-simulator .
docker tag train-simulator gcr.io/train-simulator-gcp/train-simulator
docker push gcr.io/train-simulator-gcp/train-simulator
----

[source,bash]
----
helm upgrade game-service ./charts/game-service
kubectl get pods
kubectl get services
kubectl get ingress
kubectl get ingress game-service
kubectl describe ingress game-service
kubectl get ingress game-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
----

=== Terraform

[source,bash]
----
gcloud auth application-default login
cd terraform
terraform init
terraform fmt
terraform validate
terraform graph
terraform graph -type=plan
terraform plan
terraform apply
terraform refresh
terraform output
terraform state list
terraform destroy
----

=== DNS setup

Set up the DNS records at the registrar (we could do it using Terraform, but that can wait):
[source,bash]
----
gcloud dns managed-zones describe ts-krikis-online
dig ns-cloud-a1.googledomains.com +short
dig ns-cloud-a2.googledomains.com +short
dig ns-cloud-a3.googledomains.com +short
dig ns-cloud-a4.googledomains.com +short
----

Then https://cloud.google.com/dns/docs/update-name-servers#change-name-servers[change your domain registrar's name servers].
