= Train Simulator
:toc:

== CI/CD Status

image::https://github.com/jurisk/train-simulator/actions/workflows/rust.yml/badge.svg[Rust,link=https://github.com/jurisk/train-simulator/actions/workflows/rust.yml]

https://storage.googleapis.com/ts.krikis.online/single.html[Static version]

== Useful commands

=== Full Build

On Windows:

[source,bash]
----
./bin/full-build.ps1
----

=== Housekeeping

Rare:

[source,bash]
----
rustup update
cargo update
cargo update --dry-run
cargo udeps --all-targets
cargo audit

cargo install cargo-cache
cargo cache --autoclean

cargo tree --duplicates

cargo install cargo-duplicates
cargo duplicates
----

Note - Updating `tokio` to 1.39 broke `ezsockets` or something near it.

Removing `~/.cargo/registry` is sometimes needed.

Frequent:

[source,bash]
----
cargo +nightly fmt
cargo clippy -- -W clippy::pedantic -W clippy::style -W clippy::unwrap_used -W clippy::expect_used
cargo clippy -- -W clippy::pedantic -W clippy::style -W clippy::unwrap_used -W clippy::expect_used -W unused_crate_dependencies -W unused_extern_crates -W unused_lifetimes
----

=== Running

[NOTE]
====
Do not forget to use `--features bevy/dynamic_linking` when running from the IDE.
====

[source,bash]
----
cargo build
cargo run --features bevy/dynamic_linking --package networking-server --bin server_console
cargo run --features bevy/dynamic_linking --package networking-client --bin client_graphical
cargo run --features bevy/dynamic_linking --package client-single-player --bin client_single_player
----

=== Install Prerequisites

On macOS:

[source,bash]
----
brew install llvm
----

From https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional[Enable Fast Compiles]:

[source,bash]
----
cargo install -f cargo-binutils
rustup component add llvm-tools-preview
----

From https://github.com/bevyengine/bevy/tree/main/examples#wasm[WASM examples]:

[source,bash]
----
rustup target add wasm32-unknown-unknown
cargo install wasm-bindgen-cli
----

=== WASM build

Later: Consider using `wasm-pack` and `wasm-opt` as described in https://github.com/UkoeHB/enfync?tab=readme-ov-file#recommended-wasm-build[`enfync` docs]:

[source,bash]
----
cargo build --profile wasm-release --target wasm32-unknown-unknown --package client-single-player --package networking-client --bin client_single_player --bin client_graphical
wasm-bindgen --out-name client_single_player --out-dir static/wasm-build --target web target/wasm32-unknown-unknown/wasm-release/client_single_player.wasm
wasm-bindgen --out-name client_graphical --out-dir static/wasm-build --target web target/wasm32-unknown-unknown/wasm-release/client_graphical.wasm
----

=== Dependency tree

Not sure why, but the resulting `.dot` files would open in the JetBrains IDE plug-in, but not with the `dot` command-line tool.

[source,bash]
----
cargo install cargo-depgraph
cargo depgraph --all-deps
cargo depgraph --all-deps --dedup-transitive-deps
cargo depgraph --workspace-only
dot -Tsvg input.dot -o output.svg
----

Later: Could add a CI action to check that the `--workspace-only` graph hasn't changed and isn't circular.

=== Visualise structure

Example, for the `game-logic` package:

[source,bash]
----
cargo install cargo-modules
cargo modules dependencies --no-externs --no-fns --no-sysroot --no-traits --no-types --no-uses --package game-logic > game-logic-module.dot
----

=== Profiling

See https://github.com/bevyengine/bevy/blob/main/docs/profiling.md[Bevy profiling].

In `Cargo.toml`, set:

[source,toml]
----
[profile.release]
debug = true
----

Needs to be run as admin on Windows.

[source,bash]
----
cargo install flamegraph
cargo flamegraph --bin client_single_player --features bevy/trace_chrome --root --release
cargo flamegraph --bin server_console --features bevy/trace_chrome --root --release
cargo flamegraph --bin client_graphical --features bevy/trace_chrome -- ws://127.0.0.1:8080/ws ee6b4aa1-67e0-4d6b-a42c-56320f61390e
----

=== Code size profiling

https://rustwasm.github.io/book/reference/code-size.html[Code size profiling]:

[source,bash]
----
cargo install twiggy
twiggy top -n 20 .\static\wasm-build\client_graphical_bg.wasm
twiggy paths .\static\wasm-build\client_graphical_bg.wasm
twiggy dominators .\static\wasm-build\client_graphical_bg.wasm
twiggy garbage .\static\wasm-build\client_graphical_bg.wasm
----

== Deploy locally

=== Package and run as Docker

==== Build and run the Docker image:

[source,bash]
----
docker network create train-simulator
docker build --tag train-simulator --file game-server.dockerfile .
docker run --interactive --tty --rm --name train-simulator --publish 8080:8080/tcp --network=train-simulator train-simulator
docker stop train-simulator
----

==== Run local proxy (incomplete)

[source,bash]
----
docker run --interactive --tty --rm  -d -p 80:80 -p 443:443 -p 2019:2019 --network=train-simulator --name train-simulator-proxy -v $(pwd)/Caddyfile:/etc/caddy/Caddyfile caddy
docker logs train-simulator-proxy --follow

docker build --tag train-simulator-proxy --file caddy.dockerfile .
docker run --interactive --tty --rm --name train-simulator-proxy --publish 443:443/tcp --network=train-simulator train-simulator-proxy
docker stop train-simulator-proxy
----

==== Maintenance

Pruning, as Rancher tends to eat up all available space:

[source,bash]
----
docker system prune -f
docker builder prune -f
----

== Deploy to Google Cloud Platform

=== Overall pre-requisites

Install https://cloud.google.com/sdk/docs/install-sdk[Google Cloud SDK].

[source,bash]
----
gcloud auth login
gcloud config set project train-simulator-gcp
----

=== Build and push Docker images

==== Pre-requisites:

[source,bash]
----
gcloud services enable artifactregistry.googleapis.com
gcloud auth configure-docker
----

==== Game server:

[source,bash]
----
docker build --tag train-simulator --file game-server.dockerfile .
docker tag train-simulator gcr.io/train-simulator-gcp/train-simulator
docker push gcr.io/train-simulator-gcp/train-simulator
----

==== Proxy:

[source,bash]
----
docker build --tag train-simulator-proxy --file caddy.dockerfile .
docker tag train-simulator-proxy gcr.io/train-simulator-gcp/train-simulator-proxy
docker push gcr.io/train-simulator-gcp/train-simulator-proxy
----

=== Terraform

==== Useful commands

[source,bash]
----
gcloud auth application-default login
cd terraform
terraform init
terraform fmt -recursive
terraform validate
terraform graph
terraform graph -type=plan
terraform plan
terraform apply
terraform refresh
terraform output
terraform state list
terraform destroy
terraform destroy -target module.proxy
terraform destroy -target module.game_server
----

==== DNS setup

Set up the DNS records at the registrar (we could do it using Terraform, but that can wait):

[source,bash]
----
gcloud dns managed-zones describe ts-krikis-online
dig ns-cloud-a1.googledomains.com +short
dig ns-cloud-a2.googledomains.com +short
dig ns-cloud-a3.googledomains.com +short
dig ns-cloud-a4.googledomains.com +short
----

Then https://cloud.google.com/dns/docs/update-name-servers#change-name-servers[change your domain registrar's name servers].
