= Train Simulator
:toc:

== CI/CD Status

image::https://github.com/jurisk/train-simulator/actions/workflows/rust.yml/badge.svg[Rust,link=https://github.com/jurisk/train-simulator/actions/workflows/rust.yml]

https://jurisk.github.io/train-simulator-pages/[Online version]

== Useful commands

=== Housekeeping

Rare:

[source,bash]
----
rustup update
cargo update
cargo udeps --all-targets
cargo audit
----

Frequent:

[source,bash]
----
cargo fmt
cargo clippy -- -W clippy::pedantic -W clippy::style -W clippy::unwrap_used -W clippy::expect_used
----

=== Running

[NOTE]
====
Do not forget to use `--features bevy/dynamic_linking` when running from the IDE.
====

[source,bash]
----
cargo run --features bevy/dynamic_linking --package networking-server --bin server_console
cargo run --features bevy/dynamic_linking --package networking-client --bin client_graphical
cargo run --features bevy/dynamic_linking --package client-single-player --bin client_single_player
----

=== Install Prerequisites

On macOS:

[source,bash]
----
brew install llvm
----

From https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional[Enable Fast Compiles]:

[source,bash]
----
cargo install -f cargo-binutils
rustup component add llvm-tools-preview
----

From https://github.com/bevyengine/bevy/tree/main/examples#wasm[WASM examples]:

[source,bash]
----
rustup target add wasm32-unknown-unknown
cargo install wasm-bindgen-cli
----

=== WASM build

Later: Consider using `wasm-pack` and `wasm-opt` as described in https://github.com/UkoeHB/enfync?tab=readme-ov-file#recommended-wasm-build[`enfync` docs]:

[source,bash]
----
cargo build --profile wasm-release --target wasm32-unknown-unknown --package client-single-player --package networking-client --bin client_single_player --bin client_graphical
wasm-bindgen --out-name client_single_player --out-dir client/single-player/web/wasm-build --target web target/wasm32-unknown-unknown/wasm-release/client_single_player.wasm
wasm-bindgen --out-name client_graphical --out-dir client/single-player/web/wasm-build --target web target/wasm32-unknown-unknown/wasm-release/client_graphical.wasm
----

=== Dependency tree

Not sure why, but the resulting `.dot` files would open in the JetBrains IDE plug-in, but not with the `dot` command-line tool.

[source,bash]
----
cargo install cargo-depgraph
cargo depgraph --all-deps
cargo depgraph --all-deps --dedup-transitive-deps
cargo depgraph --workspace-only
dot -Tsvg input.dot -o output.svg
----

Later: Could add a CI action to check that the `--workspace-only` graph hasn't changed and isn't circular.

=== Visualise structure

Example, for the `game-logic` package:

[source,bash]
----
cargo install cargo-modules
cargo modules dependencies --no-externs --no-fns --no-sysroot --no-traits --no-types --no-uses --package game-logic > game-logic-module.dot
----

=== Package and run as Docker

Building and running the Docker image:

[source,bash]
----
docker build --tag train-simulator .
docker image ls train-simulator
docker run --interactive --tty --rm --name train-simulator --publish 5000:5000/tcp --publish 8080:8080/tcp train-simulator
docker stop train-simulator
----

Pruning, as Rancher tends to eat up all available space:

[source,bash]
----
docker system prune -f
docker builder prune -f
----

== Deploy to Google Cloud Platform

=== Overall pre-requisites

Install https://cloud.google.com/sdk/docs/install-sdk[Google Cloud SDK].

[source,bash]
----
gcloud auth login
gcloud config set project train-simulator-gcp
----

=== Deploy to Google Compute Engine

==== Initial setup

[source,bash]
----
gcloud services enable artifactregistry.googleapis.com
gcloud services enable compute.googleapis.com
gcloud auth configure-docker
docker build --tag train-simulator .
docker tag train-simulator gcr.io/train-simulator-gcp/train-simulator
docker push gcr.io/train-simulator-gcp/train-simulator
gcloud compute instances create-with-container train-simulator-instance-1 --container-image gcr.io/train-simulator-gcp/train-simulator --zone us-east1-c --tags game-server --machine-type e2-micro
gcloud compute instances describe train-simulator-instance-1 --zone us-east1-c --format="get(machineType)"
gcloud compute ssh train-simulator-instance-1 --zone us-east1-c
----

From within the instance:

[source,bash]
----
docker ps
gcloud compute firewall-rules create allow-http --allow tcp:8080,tcp:5000 --target-tags game-server
----

==== Redeploy

[source,bash]
----
docker build --tag train-simulator .
docker tag train-simulator gcr.io/train-simulator-gcp/train-simulator
docker push gcr.io/train-simulator-gcp/train-simulator
gcloud compute instances update-container train-simulator-instance-1 --container-image gcr.io/train-simulator-gcp/train-simulator:latest --zone us-east1
gcloud compute instances describe train-simulator-instance-1 --zone us-east1-c
gcloud compute instances describe train-simulator-instance-1 --zone us-east1-c --format="get(networkInterfaces[0].accessConfigs[0].natIP)"
----

==== Stop & delete

[source,bash]
----
gcloud compute instances stop train-simulator-instance-1 --zone us-east1-c
gcloud compute instances delete train-simulator-instance-1 --zone us-east1-c
gcloud services disable compute.googleapis.com --force
----

== Deploy to Kubernetes

#TODO: Incomplete section as I figure it out.#

[source,bash]
----
helm install game-service ./helm/game-service
helm upgrade game-service ./helm/game-service
----