[package]
name = "networking-simplenet-shared"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy_simplenet = { version = "0.9.2", default-features = false, features = [] }
serde.workspace = true