[package]
name = "networking-client"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
networking-shared = { path = "../shared" }
client-graphics = {  path = "../../client/graphics" }
shared-domain = { path = "../../shared/domain" }

bevy_simplenet = { version = "0.11.0", default-features = false, features = ["bevy", "client"] }
enfync.workspace = true
bevy = { version = "0.13.2", default-features = false, features = [] }
url.workspace = true

bincode.workspace = true
serde.workspace = true
fastrand.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Location", "console"] }