apiVersion: v1
kind: Service
metadata:
  name: {{ include "game-service.fullname" . }}
  labels:
    {{- include "game-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "game-service.selectorLabels" . | nindent 4 }}
