name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - '**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # From https://github.com/Swatinem/rust-cache
      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      # From https://github.com/bevyengine/bevy/blob/latest/docs/linux_dependencies.md
      - name: Install Bevy Linux dependencies and LLD linker
        run: | 
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
          sudo apt-get install lld clang

      - name: Run tests
        working-directory: .
        run: cargo +nightly test --verbose

      - name: Clippy
        working-directory: .
        run: cargo +nightly clippy -- -W clippy::pedantic -W clippy::style -W clippy::unwrap_used -W clippy::expect_used

      - name: Build default target
        working-directory: .
        run: cargo +nightly build --verbose

      # From https://github.com/bevyengine/bevy/tree/main/examples#wasm
      - name: Install WASM prerequisites
        working-directory: .
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli

      - name: Build WASM and generate WASM bindings
        working-directory: .
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-name train-simulator --out-dir web/wasm --target web target/wasm32-unknown-unknown/release/train-simulator.wasm
