name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - '**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy

      # From https://github.com/Swatinem/rust-cache
      - name: Enable cache
        uses: Swatinem/rust-cache@v2

      # From https://github.com/bevyengine/bevy/blob/latest/docs/linux_dependencies.md
      - name: Install Bevy Linux dependencies and LLD linker
        run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
          sudo apt-get install lld clang

      # From https://github.com/bevyengine/bevy/tree/main/examples#wasm
      - name: Install WASM prerequisites
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli

      - name: Run rustfmt
        run: cargo fmt --check

      - name: Run clippy
        run: cargo clippy -- -W clippy::pedantic -W clippy::style -W clippy::unwrap_used -W clippy::expect_used

      - name: Run tests
        run: cargo test --verbose

      - name: Build default target
        run: cargo build --verbose

      - name: Build WASM target
        run: cargo build --profile wasm-release --target wasm32-unknown-unknown --verbose

      - name: Generate WASM bindings
        run: wasm-bindgen --out-name train-simulator --out-dir web/wasm --target web target/wasm32-unknown-unknown/wasm-release/train-simulator.wasm

      - name: Publish to GitHub pages at https://jurisk.github.io/train-simulator-pages/
        run: |
          git config --global user.email "jurisk@users.noreply.github.com"
          git config --global user.name "Juris"
          git clone https://jurisk:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/jurisk/train-simulator-pages.git
          cd train-simulator-pages
          git rm -rf .
          cp -r ../web/* .
          cp -r ../assets .
          git add .
          ls -laR
          git status
          commit_message="Deploy from GitHub Action - $(date +'%Y-%m-%d %H:%M:%S') - Commit ${GITHUB_SHA::7} - Job $GITHUB_RUN_ID"
          git commit -m "$commit_message"
          git push origin master
        env:
          # Should have access to the `train-simulator-pages` repository and stored in GitHub Actions `Secrets and variables` of this repository
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
